### ISSUE TITLE
question about data pre-processing

### ISSUE THREAD

**Issue by yuequnwang** [lugia-xiao/TCGN#2]
Thank you for providing such a valuable project. According to the paper, the HER2+ dataset contains a total of 32 slices. After excluding slices A1, H1, H2, and H3, there are 28 slices left. These 28 slices contain 11548 spots in total. However, the paper mentioned that the HER2+ dataset has 9612 spots. I would like to ask, what additional data selection methods were used?

**Comment by lugia-xiao** [comment]
We follow the dataset.py and descriptions as in Hist2ST and HisToGene. There is no other data selection methods used. We use all the spots except for those in the excluded slides.
